apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
spec:
  destination:
    namespace: api-gateway-system
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest/api-gateway/gateway
    repoURL: 'https://github.com/tmax-cloud/argocd-installer.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
    retry:
      limit: 3
