{{- if .Values.tls.acme.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.acme.dns.type }}-acme-crt
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"
{{/*    "helm.sh/hook-delete-policy": before-hook-creation*/}}
spec:
  secretName: {{ .Values.tls.acme.dns.type }}-acme-crt-secret
  dnsNames:
    - {{ .Values.tls.domain | quote}}
    - {{ printf "*.%s" .Values.tls.domain | quote }}
  issuerRef:
    name: {{ printf "%s-letsencrypt-%s" .Values.tls.acme.dns.type .Values.tls.acme.environment }}
    kind: Issuer
{{- end }}

{{- if .Values.tls.selfsigned.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "15"
    "helm.sh/hook-delete-policy": before-hook-creation
  name: selfsigned-crt
spec:
  secretName: selfsigned-crt-secret
  commonName: {{ .Values.tls.domain }}
  subject:
    organizations:
      - "tmax-cloud"
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "tmax-cloud"
    - {{ .Values.tls.domain | quote }}
    - {{ printf "*.%s" .Values.tls.domain | quote }}
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer
{{- end }}