# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tags:
  certManager: true

cert-manager:
  installCRDs: true
  fullnameOverride: "cert-manager"
  extraArgs:
    - "--dns01-recursive-nameservers=8.8.8.8:53"
    - "--dns01-recursive-nameservers-only"
#  image:
#    repository: imageName:Tag
#  cainjector:
#    image:
#      repository: imageName:Tag
#  webhook:
#    image:
#      repository: imageName:Tag
## 파드에 imagePullSecrets 이 없는 경우, ServiceAccount 의 imagePullSecrets 이 파드에 추가된다
## https://kubernetes.io/ko/docs/reference/access-authn-authz/service-accounts-admin/
#  global:
#    imagePullSecrets:
#      - name: regcred
#  resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
#  cainjector:
#    resources:
#      requests:
#        cpu: 100m
#        memory: 128Mi
#  webhook:
#    resources:
#      requests:
#        cpu: 100m
#        memory: 128Mi


tmax:
  createCA: true
  sleepyTime: 180
## kubectl create ns cert-manager
## kubectl create secret docker-registry regcred --docker-username=tmaxcloudck --docker-password=$PASSWD -n cert-manager
#  imagePullSecrets:
#    - name: regcred
#  resources: {}
#  resources:
#   limits:
#     cpu: 200m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi